name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-image.yml'  # optional: re-run if workflow itself changes    
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Generate a consistent tag
    - name: Set image tag
      id: vars
      run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t pravith8kmdocker/sample-node-app:${{ env.TAG }} -t pravith8kmdocker/sample-node-app:latest .

    # Step 5: Push both tags
    - name: Push Docker image
      run: |
        docker push pravith8kmdocker/sample-node-app:${{ env.TAG }}
        docker push pravith8kmdocker/sample-node-app:latest
