name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Build and tag the image
    - name: Build Docker image
      run: |
        IMAGE_NAME=pravith8kmdocker/sample-node-app
        TAG=$(date +%Y%m%d%H%M%S)
        docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .

    # Step 4: Push the image to Docker Hub
    - name: Push Docker image
      run: |
        IMAGE_NAME=pravith8kmdocker/sample-node-app
        TAG=$(date +%Y%m%d%H%M%S)
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest
